listen = ":7006"

[monitor]
namespace = "umbrella"
subsystem = "email"

[DirectMail]
version = "2015-11-23"
accessKeyId = ""
signatureMethod = "HMAC-SHA1"
signatureVersion = "1.0"
regionId = ""
timeout = "5s"

[http]
listen = ":7007"